FROM navitia/master

COPY navitia-common_*.deb ./
COPY navitia-jormungandr_*.deb ./

# install navitia-common package
RUN dpkg -i ./navitia-common_*.deb || exit 0
RUN apt-get install -f -y

# install navitia-jormun package
RUN dpkg -i ./navitia-jormungandr_*.deb || exit 0
RUN apt-get install -f -y

# install jormungandr requirements
RUN pip install --no-cache-dir -r /usr/share/jormungandr/requirements.txt

# install uwsgi
RUN pip install uwsgi

WORKDIR /usr/src/app/

HEALTHCHECK CMD curl -f http://localhost/v1/coverage || exit 1

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
CMD ["uwsgi", "--master", "--lazy-apps", "--mount", "/=jormungandr:app", "--http", "0.0.0.0:80"]
