FROM navitia/debian8_dev

COPY navitia-common*deb .
COPY navitia-tyr*.deb .
COPY navitia-ed*.deb .
COPY navitia-cities*.deb .
COPY mimirsbrunn*.deb mimirsbrunn.deb

# remove canaltp apt repo if present
RUN rm -f /etc/apt/sources.list.d/canaltp.list 

# update package list from providers
RUN apt-get update --fix-missing 

# upgrade installed packages
RUN  apt-get upgrade -y

# install navitia-common package
RUN dpkg -i ./navitia-common*.deb || exit 0
RUN apt-get install -f -y

# install navitia-tyr package
RUN dpkg -i ./navitia-tyr*.deb || exit 0
RUN apt-get install -f -y

# install navitia-ed package
RUN dpkg -i ./navitia-ed*.deb || exit 0
RUN apt-get install -f -y

# install navitia-cities package
RUN dpkg -i ./navitia-cities*.deb || exit 0
RUN apt-get install -f -y

# install navitia-mimirsbrunn package
RUN dpkg -i ./mimirsbrunn*.deb || exit 0
RUN apt-get install -f -y


# install tyr requirements
RUN pip install --no-cache-dir -r /usr/share/tyr/requirements.txt

EXPOSE 5000

COPY tyr_settings.py /

WORKDIR /usr/src/app/
RUN cp /usr/bin/manage_tyr.py /usr/src/app/manage_tyr.py

# TODO change the user to remove this ugly C_FORCE_ROOT
ENV TYR_CONFIG_FILE=/tyr_settings.py
ENV C_FORCE_ROOT=1
CMD ["celery", "worker", "-A", "tyr.tasks", "-O", "fair"]
