FROM debian:8



RUN apt-get update --fix-missing && \
    apt-get upgrade -y && \
    apt-get install -y \
                      libzmq-dev \
                      libpqxx3-dev \
                      libgoogle-perftools-dev \
                      libprotobuf-dev \
                      libproj-dev \
                      protobuf-compiler \
                      liblog4cplus-dev  \
                      libboost-chrono-dev \
                      libboost-date-time-dev \
                      libboost-filesystem-dev \
                      libboost-iostreams-dev \
                      libboost-program-options-dev \
                      libboost-regex-dev \
                      libboost-serialization-dev \
                      libboost-system-dev \
                      libboost-test-dev \
                      libboost-thread-dev \
                      libssl-dev \
                      libosmpbf-dev \
                      git   \
                      dpkg-dev \
                      debhelper \
                      python-dev \
                      python-pip \
                      cmake

#                       libgeos-c1 \
#                      netcat  \
COPY navitia /navitia
# RUN git clone https://github.com/CanalTP/navitia.git
WORKDIR /navitia
# RUN sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
# RUN git submodule update --init --recursive

RUN pip install --upgrade pip
RUN pip install -r source/jormungandr/requirements_dev.txt

RUN DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b

RUN ls ./debian/navitia-kraken
