FROM navitia/debian8_dev


# update package list from providers
RUN apt-get update --fix-missing 

# upgrade installed packages
RUN  apt-get upgrade -y



# install postgresql-client
RUN apt-get install -y postgresql-client 

COPY navitia/source/sql/alembic /usr/share/navitia/ed/alembic
COPY /navitia/source/sql/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY navitia/source/cities /usr/share/navitia/cities

COPY instances_configuration.sh /
COPY templates/* /templates/



CMD sh -x /instances_configuration.sh
