FROM navitia/debian8_dev

COPY navitia-common*.deb .
COPY navitia-jormungandr*.deb .

# remove canaltp apt repo if present
RUN rm -f /etc/apt/sources.list.d/canaltp.list 

# update package list from providers
RUN apt-get update --fix-missing 

# upgrade installed packages
RUN  apt-get upgrade -y

# install navitia-common package
RUN dpkg -i ./navitia-common*.deb || exit 0
RUN apt-get install -f -y

# install navitia-jormun package
RUN dpkg -i ./navitia-jormun*.deb || exit 0
RUN apt-get install -f -y

# install jormungandr requirements
RUN pip install --no-cache-dir -r /usr/share/jormungandr/requirements.txt

# install uwsgi
RUN pip install uwsgi

# jormun calls curl
RUN apt-get install -y curl

WORKDIR /usr/src/app/

HEALTHCHECK CMD curl -f http://localhost/v1/coverage || exit 1

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
CMD ["uwsgi", "--master", "--lazy-apps", "--mount", "/=jormungandr:app", "--http", "0.0.0.0:80"]
